### ISSUE TITLE
Chat database

### ISSUE THREAD

**Issue by CalderWhite** [asdera/Bhopppers#2]
As I was testing the functionality of "Bhop chat", I noticed that none would go through. The error on my server side terminal was as follows:

    /home/ubuntu/workspace/Bhopppers/index.js:148
       world[data.map][data.place][socket.id] = {
                                              ^
   
    TypeError: Cannot set property 'nCJiNLAt-rhv7Y20AAAA' of undefined
       at Socket.<anonymous> (/home/ubuntu/workspace/Bhopppers/index.js:148:44)
       at emitOne (events.js:77:13)
       at Socket.emit (events.js:169:7)
       at /home/ubuntu/workspace/node_modules/socket.io/lib/socket.js:503:12
       at nextTickCallbackWith0Args (node.js:420:9)
       at process._tickCallback (node.js:349:13)

I'm wondering if this has to do with I don't have the postgres database, or just a developement bug.    
FYI : the commit for adding postgres was `9ad52b0bd69749d7e48e64f1b2131512b4cbed94`.

**Comment by CalderWhite** [comment]
~Fixed
